### PR TITLE
Strip LF.

### PR DESCRIPTION
**Pull request by hbin**
Chomp the trailing LF.

### CODE REVIEW

**Comment by proofit404** [comment]
```
I wrote a hook to read the PYTHON_VERSON from the application-specific .python-version file.
```
You doesn't need to do this at all.  If you has `.python-version` file in the your project directory then any command placed in the `~/.pyenv/shims` will run on python specified in the `.python-version` file.

I use pyenv-mode-set for projects which doesn't has `.python-version` file.  For example, if I create specific python installation for that project (with `pyenv-virtualenv` tool).

**Comment by hbin** [comment]
Emmmmm... It seems doesn't work on my computer.

I use GNU Emacs 24.4.1 on my Macbook Pro, with pyenv installed by homebrew.

Have you been test it on Mac?

**Comment by proofit404** [comment]
I'm sorry but I doesn't has mac. You can test it with something like
```
$ cd /path/to/my/project
$ python
>>> import sys
>>> sys.executable
```
If this work properly then do following from emacs:
```
M-x find-file RET /path/to/my/project/some/file
M-x run-python
>>> import sys
>>> sys.executable
```
Did you add `~/.pyenv/shims/` directory to the PATH? Also you can try https://github.com/purcell/exec-path-from-shell package. As far as I know `~/.profile` doesn't loaded by login on mac.

**Comment by hbin** [comment]
Yeah, you are right.

I just tested following your instructions. It just works fine.

But, I am a heavy user of projectile. The [snippet](https://github.com/proofit404/pyenv-mode#projectile-integration) you supplies in your README file doesn't work. That's why I wrote the hooks.

(I've delete the fork repo, so I paste the hooks blew)
```lisp
(prelude-require-packages '(anaconda-mode pyenv-mode f))

(defun projectile-pyenv-mode-set ()
  "Setting PYTHON_VERSION projectile.

Reading from the application-specific .python-version file,
and set the PYTHON_VERSION to it."
  (let* ((specific-file (expand-file-name ".python-version"
                                          (projectile-project-root)))
         (specific-version (if (file-exists-p specific-file)
                               (replace-regexp-in-string
                                "\n" "" (f-read specific-file 'utf-8)))))
    (if specific-version
        (pyenv-mode-set specific-version)
      (pyenv-mode-unset))))
(add-hook 'projectile-switch-project-hook 'projectile-pyenv-mode-set)
```
The hooks just work fine with projectile.

BTW, I wrote another hook to handle `find file in projects`, It will properly set/unset the PYTHON_VERSION.
```lisp
(defun projectile-pyenv-mode-set-if ()
  "Setting PYTHON_VERSION if in `python-mode'."
  (if (and (equal major-mode 'python-mode)
           (projectile-project-p))
      (projectile-pyenv-mode-set)
    (pyenv-mode-unset)))
(add-hook 'find-file-hook 'projectile-pyenv-mode-set-if)
```

**Comment by proofit404** [comment]
Projectile snippet in the README will work if you has virtualenv with name matched your project name. For example I switch to the project `multiscanner` and there are `~/.pyenv/versions/multiscanner` virtualenv. If I specify `multiscanner` in the `.python-version` file it will be used by default.  I doesn't understand why you need to overwrite `.python-version` with `$PYENV_VERSION` with the same value.

**Pull request closed without merging**
